version: "3.3"

services:
    backend:
        build: .
        env_file: .env
        ports:
            - "9000:9000"
        links:
            - mysql
            - graphite
        volumes:
            - ./src:/var/www/html/api/2.0/
            - ./common:/var/www/html/api/common/
            - ./notifications/register.php:/var/www/html/api/notifications/register.php
            - ./dist/latest.php:/var/www/html/dist/latest.php
    datadog:
        build: datadog
        links:
         - backend
        env_file: .env
        environment:
         - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
        volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - /proc/:/host/proc/:ro
         - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    test-nginx:
        image: "nginx:latest"
        ports:
            - "8080:80"
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - backend
    mysql:
        image: "mysql:5"
        environment:
            - MYSQL_DATABASE=schoolpower
            - MYSQL_USER=schoolpower
            - MYSQL_PASSWORD=${SQL_PASSWORD}
        env_file: .env
        volumes:
            - sqldata:/var/lib/mysql
        ports:
            - "3306:3306"
    graphite:
        image: graphiteapp/graphite-statsd
        volumes:
            - graphite-conf:/opt/graphite/conf
            - graphite-data:/opt/graphite/storage
            - statsd:/opt/statsd
        ports:
            - "2003:2003"
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        environment:
            - "GF_INSTALL_PLUGINS=grafana-piechart-panel"
        links:
            - graphite
            - mysql
        volumes:
            - grafana-storage:/var/lib/grafana
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        links:
            - mysql:db
volumes:
  graphite-conf:
  graphite-data:
  grafana-storage:
  sqldata:
  statsd: