# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protos/powerschool.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto


class ProfileGender(betterproto.Enum):
    MALE = 0
    FEMALE = 1


@dataclass
class Grade(betterproto.Message):
    percentage: float = betterproto.double_field(1)
    letter: str = betterproto.string_field(2)


@dataclass
class Assignment(betterproto.Message):
    title: str = betterproto.string_field(1)
    date: int = betterproto.int64_field(2)
    grade: "Grade" = betterproto.message_field(3)
    mark_for_display: str = betterproto.string_field(4)
    category: str = betterproto.string_field(6)
    include_in_final_grade: bool = betterproto.bool_field(7)
    weight: float = betterproto.double_field(8)
    terms: List[str] = betterproto.string_field(9)
    flags: Dict[str, bool] = betterproto.map_field(
        10, betterproto.TYPE_STRING, betterproto.TYPE_BOOL
    )
    description: str = betterproto.string_field(11)
    comment: str = betterproto.string_field(12)


@dataclass
class TermGrade(betterproto.Message):
    term: str = betterproto.string_field(1)
    grade: "Grade" = betterproto.message_field(2)
    comment: str = betterproto.string_field(3)
    evaluation: str = betterproto.string_field(4)
    evaluation_code: str = betterproto.string_field(5)


@dataclass
class Course(betterproto.Message):
    name: str = betterproto.string_field(1)
    instructor: str = betterproto.string_field(2)
    instructor_email: str = betterproto.string_field(3)
    block: str = betterproto.string_field(4)
    room: str = betterproto.string_field(5)
    assignments: List["Assignment"] = betterproto.message_field(6)
    grades: List["TermGrade"] = betterproto.message_field(7)
    start_date: int = betterproto.int64_field(8)
    end_date: int = betterproto.int64_field(9)
    schedule: List["CourseSchedule"] = betterproto.message_field(10)


@dataclass
class CourseSchedule(betterproto.Message):
    start_time: int = betterproto.int64_field(1)
    end_time: int = betterproto.int64_field(2)


@dataclass
class Profile(betterproto.Message):
    gpa: float = betterproto.double_field(1)
    id: int = betterproto.int32_field(2)
    gender: "ProfileGender" = betterproto.enum_field(3)
    dob: int = betterproto.int64_field(4)
    first_name: str = betterproto.string_field(5)
    middle_name: str = betterproto.string_field(6)
    last_name: str = betterproto.string_field(7)


@dataclass
class DisabledInfo(betterproto.Message):
    title: str = betterproto.string_field(1)
    message: str = betterproto.string_field(2)


@dataclass
class ExtraInfo(betterproto.Message):
    avatar_url: str = betterproto.string_field(1)
    information_card: "InformationCard" = betterproto.message_field(2)
    jwt: str = betterproto.string_field(3)
    available_terms: List[str] = betterproto.string_field(4)


@dataclass
class Attendance(betterproto.Message):
    code: str = betterproto.string_field(1)
    date: int = betterproto.int64_field(2)
    description: str = betterproto.string_field(3)
    course_name: str = betterproto.string_field(4)
    course_block: str = betterproto.string_field(5)
    comment: str = betterproto.string_field(6)


@dataclass
class InformationCard(betterproto.Message):
    identifier: str = betterproto.string_field(1)
    title: str = betterproto.string_field(2)
    message: str = betterproto.string_field(3)
    image_url: str = betterproto.string_field(4)
    primary_text: str = betterproto.string_field(5)
    primary_on_click_url: str = betterproto.string_field(6)
    title_background_color_hex: str = betterproto.string_field(7)
    message_background_color_hex: str = betterproto.string_field(8)
    is_active: bool = betterproto.bool_field(9)


@dataclass
class StudentData(betterproto.Message):
    profile: "Profile" = betterproto.message_field(1)
    attendances: List["Attendance"] = betterproto.message_field(2)
    courses: List["Course"] = betterproto.message_field(3)
    disabled_info: "DisabledInfo" = betterproto.message_field(4)
    extra_info: "ExtraInfo" = betterproto.message_field(5)
